# Generated by Django 4.0.1 on 2022-03-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('product_type', models.CharField(choices=[('patent', 'patent'), ('generic', 'generic')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('deal', models.CharField(max_length=100)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
    ]
