# Generated by Django 4.0.1 on 2022-03-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_brand_remove_product_brand_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Firm_name', models.CharField(max_length=100)),
                ('Drug_license_number', models.CharField(max_length=100)),
                ('GSTIN', models.CharField(max_length=15)),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
    ]
