# Generated by Django 4.0.1 on 2022-03-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to='brand_logo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_image'),
        ),
    ]
