# Generated by Django 4.0.1 on 2022-03-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_category_product_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Date_Of_Billing_From_Stock',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Date_Of_Purchase_in_Stock',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='EXP_Date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='MFG_Date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Packing_Value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Stock_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
