# Generated by Django 4.0.1 on 2022-03-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_date_of_billing_from_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Supplier_detail',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
