# Generated by Django 4.0.1 on 2022-03-14 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_supplier_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_type',
            new_name='product_Quality_type',
        ),
    ]
