# Generated by Django 4.0.1 on 2022-03-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_rename_product_type_product_product_quality_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('EmailId', models.EmailField(max_length=100)),
                ('Role', models.CharField(choices=[('Customer', 'Customer'), ('Manager', 'Manager'), ('Proprietor', 'Proprietor')], max_length=100)),
                ('Password_First', models.CharField(max_length=100)),
                ('Password_Second', models.CharField(max_length=100)),
            ],
        ),
    ]
