# Generated by Django 4.0.1 on 2022-03-14 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_userlogin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogin',
            old_name='FirstName',
            new_name='UserName',
        ),
        migrations.RemoveField(
            model_name='userlogin',
            name='LastName',
        ),
    ]
