# Generated by Django 4.0.1 on 2022-03-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_userlogin_password_first_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogin',
            old_name='UserName',
            new_name='FirstName',
        ),
        migrations.AddField(
            model_name='userlogin',
            name='LastName',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
