# Generated by Django 4.0.1 on 2022-03-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_rename_username_userlogin_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='password1',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlogin',
            name='password2',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
