# Generated by Django 4.0.1 on 2022-03-14 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_userlogin_password1_userlogin_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='userlogin',
            name='LastName',
        ),
        migrations.RemoveField(
            model_name='userlogin',
            name='Role',
        ),
    ]
